#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod bn254;
pub mod context_upgradeable;
pub mod erc1967_utils;
pub mod example_rollup;
pub mod i_beacon;
pub mod i_plonk_verifier;
pub mod ierc1822_proxiable;
pub mod initializable;
pub mod light_client;
pub mod light_client_state_update_vk;
pub mod ownable_upgradeable;
pub mod plonk_verifier;
pub mod polynomial_eval;
pub mod shared_types;
pub mod storage_slot;
pub mod utils;
pub mod uups_upgradeable;
